# Generated by Django 3.1.1 on 2020-09-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Higher Level', 'PL'), ('School Level', 'SC'), ('Other', 'OL')], default='Other', max_length=20),
        ),
    ]
