# Generated by Django 3.1.1 on 2020-09-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200910_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug_field',
            new_name='slug',
        ),
    ]
