# Generated by Django 3.1.1 on 2020-09-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200910_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Images',
            field=models.ImageField(blank=True, default='product/output-onlinepngtools_4_m0DaNEc.png', null=True, upload_to='product'),
        ),
    ]
