# Generated by Django 3.1.1 on 2020-09-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200911_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature_image',
            field=models.ImageField(blank=True, default='product/output-onlinepngtools_4_m0DaNEc.png', upload_to='product'),
        ),
    ]
